### ISSUE TITLE
hello folks, this is our 'web site'

### ISSUE THREAD

**Issue by helio-frota** [EsmerilProgramming/esmerilprogramming.github.io#1]
http://esmerilprogramming.github.io/

anyone is welcome to push updates, improve the 'site', write about a project or issue etc
we can use the github issues to do the communication instead use disqus or others platforms ( are cool but need maintenance )

maybe I'm going to publish my personal agenda there by creating a separated html page

**Comment by htmfilho** [comment]
Very good! (inc 1)

**Comment by felipewmartins** [comment]
+1 Very good :D

2015-05-25 16:16 GMT-03:00 Hildeberto Mendonça notifications@github.com:

> Very good! (inc 1)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EsmerilProgramming/esmerilprogramming.github.io/issues/1#issuecomment-105292185
> .

## 

Felipe Wender Mendonça Martins
Graduando em Análise e Desenvolvimento de Sistemas
#blog: http://felipewmartins.github.io/
Fatene

**Comment by helio-frota** [comment]
glad you guys liked
feel free to push some content as you like, and/or take care of layout (i don't care about this) you know i'm freak sometimes, but this space is our space.

Since this is a 'learning fun hacking group' I will publish my sources of learning on my page. (books , blogs, docs etc..)

( is good everyone take care of your own page , we can visit the page each push to see the updates ofc )

most important thing: HAVE FUN !

**Comment by helio-frota** [comment]
first 'post'

http://esmerilprogramming.github.io/index.html

**Comment by helio-frota** [comment]
I can't keep an agenda : //
I do it for FUN , discipline for me is on the job... OpenSource == FUN

https://github.com/eprogramming/0_o/blob/master/O_o.java

**Comment by helio-frota** [comment]
Hi all look what @efraimgentil did !
f.... awesome !

http://esmerilprogramming.github.io/

**Comment by helio-frota** [comment]
@stalep 

https://www.youtube.com/watch?v=YmGoqQvGyBw

**Comment by efraimgentil** [comment]
\o/ still a work in progress, i'm still learning this jekyll thing =)

**Comment by helio-frota** [comment]
np @efraimgentil : ]

**Comment by helio-frota** [comment]
https://www.youtube.com/watch?v=icZTg2rNvVY
